# load_folder: debug_2024-06-24_15-22-31
# load_number: 8
load_folder: null 
load_number: null

# pickle_file_name: debug/debug_2024-07-17_08-48-50.pkl
pickle_file_name: null

rerun: true
open_communication: true
static: true

min_depth: 0.25
max_depth: 2.0
